apiVersion: storage.gcp.upbound.io/v1beta1
kind: ObjectACL
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/objectacl
    upjet.upbound.io/manual-intervention: "Needs permissions for provide access to ACL"
  labels:
    testing.upbound.io/example-name: image-store-acl
  name: image-store-acl
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: bucket
    objectSelector:
      matchLabels:
        testing.upbound.io/example-name: image
    roleEntity:
      - OWNER:allUsers

---

apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/objectacl
  labels:
    testing.upbound.io/example-name: bucket
  name: bucket-${Rand.RFC1123Subdomain}
spec:
  forProvider:
    cors:
      - maxAgeSeconds: 3600
        method:
          - GET
          - HEAD
          - PUT
          - POST
          - DELETE
        origin:
          - http://image-store.com
        responseHeader:
          - '*'
    forceDestroy: true
    location: US
    uniformBucketLevelAccess: true
    website:
      - mainPageSuffix: index.html
        notFoundPage: 404.html

---

apiVersion: storage.gcp.upbound.io/v1beta1
kind: BucketObject
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/objectacl
  labels:
    testing.upbound.io/example-name: image
  name: image
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: bucket
    name: bucket-object
    content: "Upbound!"
    contentType: text/plain
