apiVersion: certificatemanager.gcp.upbound.io/v1beta1
kind: Certificate
metadata:
  annotations:
    meta.upbound.io/example-id: certificatemanager/v1beta1/certificate
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    description: The default cert
    scope: EDGE_CACHE
    selfManaged:
    - pemCertificate: ${file("test-fixtures/certificatemanager/cert.pem")}
      pemPrivateKeySecretRef:
        key: attribute.private-key.pem
        name: example-secret
        namespace: upbound-system

---

