apiVersion: certificatemanager.gcp.upbound.io/v1beta1
kind: CertificateMapEntry
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: "Certificate requires a real certificate ID and depends on resources with manual intervention annotation"
    meta.upbound.io/example-id: certificatemanager/v1beta1/certificatemapentry
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    certificates:
    - projects/official-provider-testing/locations/global/certificates/certificate
    description: My acceptance test certificate map entry
    labels:
      acc-test: "true"
      terraform: "true"
    mapSelector:
      matchLabels:
        testing.upbound.io/example-name: certificate_map
    matcher: PRIMARY

---

apiVersion: certificatemanager.gcp.upbound.io/v1beta1
kind: Certificate
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: "Certificate requires a real DNS authorization ID"
    meta.upbound.io/example-id: certificatemanager/v1beta1/certificatemapentry
  labels:
    testing.upbound.io/example-name: certificate
  name: certificate
spec:
  forProvider:
    description: The default cert
    managed:
    - dnsAuthorizations:
      - projects/official-provider-testing/locations/global/dnsAuthorizations/instance
      - projects/official-provider-testing/locations/global/dnsAuthorizations/instance2
      domains:
      - subdomain2.hashicorptest.com
      - subdomain.hashicorptest.com
    scope: DEFAULT

---

apiVersion: certificatemanager.gcp.upbound.io/v1beta1
kind: CertificateMap
metadata:
  annotations:
    meta.upbound.io/example-id: certificatemanager/v1beta1/certificatemapentry
  labels:
    testing.upbound.io/example-name: certificate_map
  name: certificate-map
spec:
  forProvider:
    description: My acceptance test certificate map
    labels:
      acc-test: "true"
      terraform: "true"

---

apiVersion: certificatemanager.gcp.upbound.io/v1beta1
kind: DNSAuthorization
metadata:
  annotations:
    meta.upbound.io/example-id: certificatemanager/v1beta1/certificatemapentry
  labels:
    testing.upbound.io/example-name: instance
  name: instance
spec:
  forProvider:
    description: The default dnss
    domain: subdomain.hashicorptest.com

---

apiVersion: certificatemanager.gcp.upbound.io/v1beta1
kind: DNSAuthorization
metadata:
  annotations:
    meta.upbound.io/example-id: certificatemanager/v1beta1/certificatemapentry
  labels:
    testing.upbound.io/example-name: instance2
  name: instance2
spec:
  forProvider:
    description: The default dnss
    domain: subdomain2.hashicorptest.com

