apiVersion: eventarc.gcp.upbound.io/v1beta1
kind: GoogleChannelConfig
metadata:
  annotations:
    meta.upbound.io/example-id: eventarc/v1beta1/googlechannelconfig
  labels:
    testing.upbound.io/example-name: primary
  name: primary
spec:
  forProvider:
    location: us-west1